{{- if .Values.app.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "django-app.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.app.config | nindent 2 }}
{{- end }}
