apiVersion: v1
kind: Service
metadata:
  name: {{ include "django-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      {{- if and (eq .Values.app.service.type "NodePort") .Values.app.service.nodePort }}
      nodePort: {{ .Values.app.service.nodePort }}
      {{- end }}
  selector:
    {{- include "django-app.selectorLabels" . | nindent 4 }}
